import {Outfit} from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./Provider";


const outfit = Outfit({subsets:["latin"]})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <ClerkProvider>

      <body
        className={outfit.className}
        >
          <Provider>

        {children}
          </Provider>
      </body>
        </ClerkProvider>
    </html>
  );
}
